### ISSUE TITLE
Set a default format for single-click

### ISSUE THREAD

**Issue by timheuer** [jeffhandley/copy-github-link#10]
I love all the verbose options, but also want a fast "give me the link in a default preferred format" way.

Single-click copy with my own default.
Still allow me to drop-down to more verbose option.

**Comment by jeffhandley** [comment]
@timheuer This is now implemented with #12 and version 1.3.0 is pending publication to the [chrome web store](https://chromewebstore.google.com/detail/copy-github-link/dnfnnlockpehnpkfdbejdogbfkjfeaan).
