### ISSUE TITLE
Text is hard to read in dark mode

### ISSUE THREAD

**Issue by mthalman** [jeffhandley/copy-github-link#21]
I use GitHub set to dark mode. The header text appears very light in that mode. See screenshot:
![image](https://github.com/user-attachments/assets/543e9fea-69cc-42b1-9dc3-7df2135cec25)

**Comment by jeffhandley** [comment]
This fix will be in version 1.3.8, which was submitted for publishing.

**Comment by mthalman** [comment]
Thanks! Looks great now.
