### ISSUE TITLE
[Feature Request] Support copying links to issues/PRs when viewing as child item on a project

### ISSUE THREAD

**Issue by jeffhandley** [jeffhandley/copy-github-link#25]
When viewing a project and expanding the details of an issue or pull request within the project view, the issue/PR details pane does not show a button to copy the link to that issue/PR.

**Comment by rainersigwald** [comment]
It looks like GitHub itself added such a button (next to the edit button here):

<img width="238" alt="image" src="https://github.com/user-attachments/assets/1090988e-e025-4654-b41c-276fc7610316">

But it just copies the URL. Maybe this extension could override that behavior? But I couldn't figure out (in a minute or two) what clicking that button actually calls.

**Comment by jeffhandley** [comment]
@eerhardt This support is added in version 1.4.0. I'll get it published later today.
